Update dependencies on libxfcegui4 version and libxfce4mcs
(Old svn revision: 3480)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS VERSION INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EGREP MY_SUBDIRS GLIB_REQUIRED_VERSION GTK_REQUIRED_VERSION PANGO_REQUIRED_VERSION LIBXFCEGUI4_REQUIRED_VERSION PKG_CONFIG BASE_DEPENDENCIES_CFLAGS BASE_DEPENDENCIES_LIBS MCS_CLIENT_CFLAGS MCS_CLIENT_LIBS MCS_MANAGER_CFLAGS MCS_MANAGER_LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO RANLIB ac_ct_RANLIB LIBTOOL LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS VERSION INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EGREP MY_SUBDIRS GLIB_REQUIRED_VERSION GTK_REQUIRED_VERSION PANGO_REQUIRED_VERSION LIBXFCEGUI4_REQUIRED_VERSION LIBXFCE4MCS_REQUIRED_VERSION PKG_CONFIG BASE_DEPENDENCIES_CFLAGS BASE_DEPENDENCIES_LIBS MCS_CLIENT_CFLAGS MCS_CLIENT_LIBS MCS_MANAGER_CFLAGS MCS_MANAGER_LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO RANLIB ac_ct_RANLIB LIBTOOL LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4898,7 +4898,8 @@ fi;
 GLIB_REQUIRED_VERSION=2.0.0
 GTK_REQUIRED_VERSION=2.0.0
 PANGO_REQUIRED_VERSION=1.0.0
-LIBXFCEGUI4_REQUIRED_VERSION=0.0.7
+LIBXFCEGUI4_REQUIRED_VERSION=0.0.10
+LIBXFCE4MCS_REQUIRED_VERSION=0.0.1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -4919,6 +4920,12 @@ _ACEOF
 cat >>confdefs.h <<_ACEOF
 #define LIBXFCEGUI4_REQUIRED_VERSION $LIBXFCEGUI4_REQUIRED_VERSION
 _ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define LIBXFCE4MCS_REQUIRED_VERSION $LIBXFCE4MCS_REQUIRED_VERSION
+_ACEOF
+
 
 
 
@@ -5079,23 +5086,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfce4mcs-client-1.0" >&5
-echo $ECHO_N "checking for libxfce4mcs-client-1.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION" >&5
+echo $ECHO_N "checking for libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfce4mcs-client-1.0" ; then
+        if $PKG_CONFIG --exists "libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking MCS_CLIENT_CFLAGS" >&5
 echo $ECHO_N "checking MCS_CLIENT_CFLAGS... $ECHO_C" >&6
-            MCS_CLIENT_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-client-1.0"`
+            MCS_CLIENT_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION"`
             echo "$as_me:$LINENO: result: $MCS_CLIENT_CFLAGS" >&5
 echo "${ECHO_T}$MCS_CLIENT_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking MCS_CLIENT_LIBS" >&5
 echo $ECHO_N "checking MCS_CLIENT_LIBS... $ECHO_C" >&6
-            MCS_CLIENT_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-client-1.0"`
+            MCS_CLIENT_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION"`
             echo "$as_me:$LINENO: result: $MCS_CLIENT_LIBS" >&5
 echo "${ECHO_T}$MCS_CLIENT_LIBS" >&6
         else
@@ -5103,7 +5110,7 @@ echo "${ECHO_T}$MCS_CLIENT_LIBS" >&6
             MCS_CLIENT_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            MCS_CLIENT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-client-1.0"`
+            MCS_CLIENT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION"`
             echo $MCS_CLIENT_PKG_ERRORS
         fi
 
@@ -5118,8 +5125,8 @@ echo "${ECHO_T}$MCS_CLIENT_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-client-1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfce4mcs-client-1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfce4mcs-client-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -5177,23 +5184,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfce4mcs-manager-1.0" >&5
-echo $ECHO_N "checking for libxfce4mcs-manager-1.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION" >&5
+echo $ECHO_N "checking for libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfce4mcs-manager-1.0" ; then
+        if $PKG_CONFIG --exists "libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking MCS_MANAGER_CFLAGS" >&5
 echo $ECHO_N "checking MCS_MANAGER_CFLAGS... $ECHO_C" >&6
-            MCS_MANAGER_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-manager-1.0"`
+            MCS_MANAGER_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION"`
             echo "$as_me:$LINENO: result: $MCS_MANAGER_CFLAGS" >&5
 echo "${ECHO_T}$MCS_MANAGER_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking MCS_MANAGER_LIBS" >&5
 echo $ECHO_N "checking MCS_MANAGER_LIBS... $ECHO_C" >&6
-            MCS_MANAGER_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-manager-1.0"`
+            MCS_MANAGER_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION"`
             echo "$as_me:$LINENO: result: $MCS_MANAGER_LIBS" >&5
 echo "${ECHO_T}$MCS_MANAGER_LIBS" >&6
         else
@@ -5201,7 +5208,7 @@ echo "${ECHO_T}$MCS_MANAGER_LIBS" >&6
             MCS_MANAGER_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            MCS_MANAGER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-manager-1.0"`
+            MCS_MANAGER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION"`
             echo $MCS_MANAGER_PKG_ERRORS
         fi
 
@@ -5216,8 +5223,8 @@ echo "${ECHO_T}$MCS_MANAGER_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-manager-1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfce4mcs-manager-1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfce4mcs-manager-1.0 >= $LIBXFCE4MCS_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -6425,7 +6432,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6428 "configure"' > conftest.$ac_ext
+  echo '#line 6435 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6939,7 +6946,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6942: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:6949: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8713,7 +8720,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8716 "configure"
+#line 8723 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8811,7 +8818,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8814 "configure"
+#line 8821 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10224,6 +10231,7 @@ s,@GLIB_REQUIRED_VERSION@,$GLIB_REQUIRED_VERSION,;t t
 s,@GTK_REQUIRED_VERSION@,$GTK_REQUIRED_VERSION,;t t
 s,@PANGO_REQUIRED_VERSION@,$PANGO_REQUIRED_VERSION,;t t
 s,@LIBXFCEGUI4_REQUIRED_VERSION@,$LIBXFCEGUI4_REQUIRED_VERSION,;t t
+s,@LIBXFCE4MCS_REQUIRED_VERSION@,$LIBXFCE4MCS_REQUIRED_VERSION,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
 s,@BASE_DEPENDENCIES_CFLAGS@,$BASE_DEPENDENCIES_CFLAGS,;t t
 s,@BASE_DEPENDENCIES_LIBS@,$BASE_DEPENDENCIES_LIBS,;t t
